// Re-export all view components for better TypeScript support
export { default as HomeView } from './HomeView.vue'
export { default as NotFoundView } from './NotFoundView.vue'
export { default as AssessmentView } from './AssessmentView.vue'
export { default as AssessmentList } from './AssessmentList.vue'
export { default as CreateAssessmentView } from './CreateAssessmentView.vue'
export { default as ShareView } from './ShareView.vue'
export { default as CompiledSubmissionView } from './CompiledSubmissionView.vue'
export { default as CorrectionGridView } from './CorrectionGridView.vue'
export { default as StudentView } from './StudentView.vue'
export { default as SubjectView } from './SubjectView.vue'
